version: 2.1

defaults: &defaults

  working_directory: ~/ff1randomizer
  docker:
    - image: fiendsoftheelements/netlify-build:alpine

orbs:
  shellcheck: circleci/shellcheck@1.3.16

jobs:
  build:
    working_directory: ~/ff1randomizer
    docker:
      - image: fiendsoftheelements/netlify-build:alpine
    steps:
      - checkout
      - run:
          name: publish
          command: sh .circleci/build.sh
      - persist_to_workspace:
          root: ~/ff1randomizer/FF1Blazorizer/output
          paths:
            - wwwroot

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ff1randomizer/FF1Blazorizer/output
      - run:
          name: deploy
          command: sh .circleci/deploy.sh

workflows:
  main:
    jobs:
      - shellcheck/check:
          path: ".circleci/"
      - build:
          requires:
            - shellcheck/check
      - hold:
          type: approval
      - deploy:
          requires:
            - hold
            - build
